# Generated by Django 5.0.6 on 2024-06-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_aleatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
