# Generated by Django 5.0.6 on 2024-06-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0003_alter_commentaire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
