# Generated by Django 5.0.6 on 2024-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0004_alter_commentaire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
