# Generated by Django 5.0.6 on 2024-06-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0005_alter_formation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
